/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef } from "react";

const HELIX_SPEED = 6;

export function Airplane(props) {
  const { nodes, materials } = useGLTF("./models/airplane/plane.glb");

  const helix = useRef();

  // useFrame((_state, delta) => {
  //   helix.current.rotation.x += delta * HELIX_SPEED;
  // });

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1111588455.geometry}>
        <meshStandardMaterial color="white" />
      </mesh>
      {/* <mesh
        ref={helix}
        geometry={nodes.group1111588455.geometry}
        material={materials.mat21}
        position={[1.09, 0.23, 0]}
      >
        <meshStandardMaterial color="white" />
      </mesh> */}
    </group>
  );
}

useGLTF.preload("./models/airplane/plane.glb");
